/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/muksee/k8s-example-controller-crd/pkg/apis/samplecrd/v1"
	scheme "github.com/muksee/k8s-example-controller-crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkSpecsGetter has a method to return a NetworkSpecInterface.
// A group's client should implement this interface.
type NetworkSpecsGetter interface {
	NetworkSpecs(namespace string) NetworkSpecInterface
}

// NetworkSpecInterface has methods to work with NetworkSpec resources.
type NetworkSpecInterface interface {
	Create(ctx context.Context, networkSpec *v1.NetworkSpec, opts metav1.CreateOptions) (*v1.NetworkSpec, error)
	Update(ctx context.Context, networkSpec *v1.NetworkSpec, opts metav1.UpdateOptions) (*v1.NetworkSpec, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.NetworkSpec, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.NetworkSpecList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NetworkSpec, err error)
	NetworkSpecExpansion
}

// networkSpecs implements NetworkSpecInterface
type networkSpecs struct {
	client rest.Interface
	ns     string
}

// newNetworkSpecs returns a NetworkSpecs
func newNetworkSpecs(c *SamplecrdV1Client, namespace string) *networkSpecs {
	return &networkSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the networkSpec, and returns the corresponding networkSpec object, and an error if there is any.
func (c *networkSpecs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.NetworkSpec, err error) {
	result = &v1.NetworkSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkspecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkSpecs that match those selectors.
func (c *networkSpecs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NetworkSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NetworkSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkSpecs.
func (c *networkSpecs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("networkspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a networkSpec and creates it.  Returns the server's representation of the networkSpec, and an error, if there is any.
func (c *networkSpecs) Create(ctx context.Context, networkSpec *v1.NetworkSpec, opts metav1.CreateOptions) (result *v1.NetworkSpec, err error) {
	result = &v1.NetworkSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("networkspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkSpec).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a networkSpec and updates it. Returns the server's representation of the networkSpec, and an error, if there is any.
func (c *networkSpecs) Update(ctx context.Context, networkSpec *v1.NetworkSpec, opts metav1.UpdateOptions) (result *v1.NetworkSpec, err error) {
	result = &v1.NetworkSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networkspecs").
		Name(networkSpec.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkSpec).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the networkSpec and deletes it. Returns an error if one occurs.
func (c *networkSpecs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkspecs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkSpecs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkspecs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched networkSpec.
func (c *networkSpecs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NetworkSpec, err error) {
	result = &v1.NetworkSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("networkspecs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
