/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	samplecrdv1 "github.com/muksee/k8s-example-controller-crd/pkg/apis/samplecrd/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkSpecs implements NetworkSpecInterface
type FakeNetworkSpecs struct {
	Fake *FakeSamplecrdV1
	ns   string
}

var networkspecsResource = schema.GroupVersionResource{Group: "samplecrd.k8s.io", Version: "v1", Resource: "networkspecs"}

var networkspecsKind = schema.GroupVersionKind{Group: "samplecrd.k8s.io", Version: "v1", Kind: "NetworkSpec"}

// Get takes name of the networkSpec, and returns the corresponding networkSpec object, and an error if there is any.
func (c *FakeNetworkSpecs) Get(ctx context.Context, name string, options v1.GetOptions) (result *samplecrdv1.NetworkSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkspecsResource, c.ns, name), &samplecrdv1.NetworkSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NetworkSpec), err
}

// List takes label and field selectors, and returns the list of NetworkSpecs that match those selectors.
func (c *FakeNetworkSpecs) List(ctx context.Context, opts v1.ListOptions) (result *samplecrdv1.NetworkSpecList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkspecsResource, networkspecsKind, c.ns, opts), &samplecrdv1.NetworkSpecList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NetworkSpecList), err
}

// Watch returns a watch.Interface that watches the requested networkSpecs.
func (c *FakeNetworkSpecs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkspecsResource, c.ns, opts))

}

// Create takes the representation of a networkSpec and creates it.  Returns the server's representation of the networkSpec, and an error, if there is any.
func (c *FakeNetworkSpecs) Create(ctx context.Context, networkSpec *samplecrdv1.NetworkSpec, opts v1.CreateOptions) (result *samplecrdv1.NetworkSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkspecsResource, c.ns, networkSpec), &samplecrdv1.NetworkSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NetworkSpec), err
}

// Update takes the representation of a networkSpec and updates it. Returns the server's representation of the networkSpec, and an error, if there is any.
func (c *FakeNetworkSpecs) Update(ctx context.Context, networkSpec *samplecrdv1.NetworkSpec, opts v1.UpdateOptions) (result *samplecrdv1.NetworkSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkspecsResource, c.ns, networkSpec), &samplecrdv1.NetworkSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NetworkSpec), err
}

// Delete takes name of the networkSpec and deletes it. Returns an error if one occurs.
func (c *FakeNetworkSpecs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(networkspecsResource, c.ns, name), &samplecrdv1.NetworkSpec{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkSpecs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkspecsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &samplecrdv1.NetworkSpecList{})
	return err
}

// Patch applies the patch and returns the patched networkSpec.
func (c *FakeNetworkSpecs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *samplecrdv1.NetworkSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkspecsResource, c.ns, name, pt, data, subresources...), &samplecrdv1.NetworkSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecrdv1.NetworkSpec), err
}
